repos:
  - repo: https://gitlab.com/papanito/git-hooks.git
    rev: v2.2.3
    hooks:
      - id: get_shared_config
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  # Terraform stuff
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_trivy
  # Helm Stuff
  - repo: https://github.com/papanito/helm-pre-commit
    rev: v1.0.0
    hooks:
      - id: helm-template-all
  # Python stuff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
